// Q1
// for(var i =1; i<=10; i++){
//     // document.write(i)
//     console.log(i)
// }
// // Q2
// var userInput = +prompt("Enter a number to generate a multiplication table");
// var userInputLength = +prompt("Enter length");

// for (var i = 1; i <= userInputLength; i++) {
//   document.write(userInput + "x" + i + "=" + userInput * i + "<br>");
// }
// // Q3
// for(var i =1; i<=10; i++){
//     document.write(i )
// }
// for(var i =10; i>=1; i--){
//   document.write(i)
// }
// // Home Work  \\
// // Q1
// for(var p =1; p<=10; p++){
//   "<br>" +document.write("<br>", "Welcome User" , p , "<br>" ) 
// }


// Q2
// for( var i = range(12) );{
//  alert("Your code for each iteration here")
// }

// Q3
// for (var i = 0; i <= 4; i++){
//   document.write(i , "<br>")
// }
// Q4
// for(var i = 1; i<= 100 ; i++){
//   document.write("Ubaidraza" , "<br>")
// }
// Q6
var my_array = [1, 2, 3, 4, 5]
document.write(my_array)
// Q7
// var num =["Ubaidraza", "Mohtashim" , "Zain"]
// console.log(num)
// Q8
var arr =["Ubaidraza"]
for (var i= 0; i<arr.length; i++ ){
    console.log("F hy")
}
// Q11
// for (var i = 0; i <20; i++) {
//   if (userInput === 20[i]) {
//     alert("Match found");
//     matchFound = true; break;
// }
// };
// // Q12
// var firstArr = ["a", "b", "c", "d", "e", "f"];
//  var secondArr = [1, 2,3, 4, 5, 6];
// console.log(firstArr+secondArr)